### ISSUE TITLE
ThirdPartyMailer does not compile with XCode13beta3

### ISSUE THREAD

**Issue by iosdev-mk** [vtourraine/ThirdPartyMailer#26]
When I try to compile my project, which has **ThirdPartyMailer V1.7.1** as an SPM dependency, i get the following errors in **XCode13beta3**:

**Type 'UIApplication' does not conform to protocol 'UIApplicationOpenURLProtocol'**
Unavailable instance method 'openURL' was used to satisfy a requirement of protocol 'UIApplicationOpenURLProtocol'

The **deployment target is iOS13.0.**

With Xcode 12.5 the project does compile without any issues.

**Comment by DesmanLead** [comment]
Switching to [`open(_:options:completionHandler:)`](https://developer.apple.com/documentation/uikit/uiapplication/1648685-open) may fix this

**Comment by vtourraine** [comment]
Thanks for raising this issue!

That’s a bit surprising, the first betas were compiling just fine, and I don’t think the `UIApplication` interface should change with iOS 15. Maybe it’s a bug? Otherwise, I’d love to understand _why_ that code no longer compiles.

Anyway, we should update to `open(_:options:completionHandler:)`, it just means passing the library deployment target to iOS 10.

**Comment by vtourraine** [comment]
This branch should address the problem: https://github.com/vtourraine/ThirdPartyMailer/tree/new-open-url-interface

(this breaks the library interface, so we’ll release it as a “2.0” release)

**Comment by vtourraine** [comment]
The `new-open-url-interface` branch has been merged to `main` (not tagged as a proper release yet). But now I’m not so sure it fixes the problem here.

I understand what changed with Xcode 13 beta 3: [as discussed here](https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/11), SPM now builds with the “extension API only” option turned on. This is a problem when using `UIApplication`. But because this library is using an `extension` on `UIApplication`, I don’t think we can use a `@available` statement.

If someone has a better explanation, I’d be interested to hear it.

**Comment by vtourraine** [comment]
As I suspected above, the current implementation of having a `UIApplicationOpenURLProtocol` was basically incompatible with Xcode 13 SPM compilation parameters. It was only used for unit tests, so I’ve decided to simply remove these parameters. That means the library should now be compatible with Xcode 13.

Please check the latest version from `main` (in Xcode, you can configure a package dependency to match a branch), before we can officially tag it as “version 2”.

**Comment by iosdev-mk** [comment]
Hi Vicent,

I can confirm that with the “main“ branch of thirdpartymailer there are no Issues with XCode13.

Thanks a lot and best regards,

Martin

**Comment by vtourraine** [comment]
@iosdev-mk Awesome, thanks for the confirmation 🙌

**Comment by iosdev-mk** [comment]
Sorry, I did just check the SPM issue so far.

I got this error when compiling the code:

**Comment by iosdev-mk** [comment]
Oh, I have to change my implementation too …

**Comment by iosdev-mk** [comment]
After I used the new API (of the main-Branch) to retrieve the clients and openCompose it works on XCode13beta4.

Best regards,

Martin

**Comment by vtourraine** [comment]
Oh right, this will be released as a “version 2”, so there are some important syntax changes (the features remain the same, though). Glad to hear it’s fixed 👍
