### ISSUE TITLE
Convert to Swift 4.1

### ISSUE THREAD

**Issue by richardtop** [vtourraine/ThirdPartyMailer#3]

**Comment by vtourraine** [comment]
Hi, and thank you for reaching out.

I think we should update this library to Swift 4.0 first, and wait a bit for Swift 4.1 (it would basically require Xcode 9.3/macOS 10.13, which can still be problematic for now).

Feel free to send a pull request for 4.0. We can also create a branch for 4.1, but I wouldn’t release that (i.e. tag version for CocoaPods) just yet.

**Comment by richardtop** [comment]
Hi, why is it a problem to convert it to 4.1 straight away? Xcode 9.3 is already a mainstream.

**Comment by vtourraine** [comment]
Xcode 9.3 requires High Sierra, and a significant number of people cannot or don’t want to update yet. 

But my point is: I would prefer an update to Swift 4.0 first, then we can take care of 4.1. I’m sure the changes are small, if not non-existent, so that shouldn’t be a problem. Just need to find the time to address that.

**Comment by richardtop** [comment]
Thank you for your reply. Different "Releases" for each version should solve these issues. Looking forward to the newest update. Would be also cool to add an "UI Companion" library showing a action sheet / popup with options. But not in this repository of course.

**Comment by vtourraine** [comment]
I’ve just release ThirdPartyMailer 1.3, now based on Swift 4.2.
