### ISSUE TITLE
Outlook mail app

### ISSUE THREAD

**Issue by Disconnecter** [vtourraine/ThirdPartyMailer#33]
Outlook mail app is not handled as available but it's possible to open the app in the example app
ios 15.6.1

https://user-images.githubusercontent.com/1481512/192348698-2eb1b625-4a99-4a12-871a-60e10bad836a.mov

**Comment by vtourraine** [comment]
Hello Serg, and thanks a lot for reporting this issue.

I believe the problem was that the Outlook custom URL scheme wasn’t listed in the Example app `LSApplicationQueriesSchemes` array. It should be fixed now (I also fixed the Dark Mode support, because apparently this Example project was created before that was a thing 😅)
