### ISSUE TITLE
Converting to Objective C. 

### ISSUE THREAD

**Issue by Seoras** [vtourraine/ThirdPartyMailer#4]
I wanted to use this but the projects I wanted to use it in are ObjC. 
Due to the other open issue of the code being written in Swift v2 making the complexity greater
I decided to try rewrite it in Objective C since it's only 2 short files.
Happy to share if anyone wants it? 
Perhaps it could be added to this project and the mail client values stored in a .plist?

While converting ThirdPartyMailClient.swift to ObjC I noticed that there's a potential bug on line 102.

`components = URLComponents(string: "\(URLScheme):\(URLRoot ?? "")\(recipient)")`

This executes only if `URLRecipientKey == nil` but there's no check for URLRoot being Nil. At the moment there is only 1 case of URLRecipientKey being Nil (Sparrow) which also just happens to have URLRoot Nil too. 
If URLRecipientKey is Nil & URLRoot is not then you'll get something like:

> scheme:URLRoot[to]

There should be a separator between them. In ObjC I've written it like this:

`NSURLComponents *components;`
`    if (_URLRecipientKey == Nil) {`
`        components = [[NSURLComponents alloc] initWithString:[NSString stringWithFormat:@"%@:%@%@",_URLScheme,_URLRoot == Nil ? @"" : [NSString stringWithFormat:@"%@%@",_URLRoot, recipient ? @"/":@""], recipient]];`
`    } else {`
`        components = [[NSURLComponents alloc] initWithString:[NSString stringWithFormat:@"%@:%@",_URLScheme,_URLRoot == Nil ? @"" : _URLRoot]];`
` }`
`[components setScheme:_URLScheme];`

It's probably a moot point now since Sparrow has been discontinued.

In ThirdPartyMailer.swift I don't understand why you needed to subclass UIApplication?
You are using openURL which is deprecated.
Would be nice to update to the new version and make use of it's completion handler block in the next update.

The _README.md_ **How to use** should include the need to update the application `LSApplicationQueriesSchemes` with each supported mail client's scheme.

Finally does anyone know how to get newline's into the body of the text?
Using \n in my body string get's stripped out by NSURLQueryItem's queryItemWithName:
I've tried using \\\n and %0A but neither works.
Perhaps it works fine in Swift. It's an open issue in my ObjC implementation.

**Comment by vtourraine** [comment]
Hello,

Thanks a lot for the feedback! (next time, please try to split your questions in dedicated issues, it would make it a lot easier for me to answer them, and for other people to find the relevant discussion).

- Objective-C version: I would prefer to keep this repo Swift-only, but feel free to publish your Objective-C rewrite.
- `URLRoot` being nil: I use the “nil-coalescing operator” (`??`), so that case should actually be covered
- subclass `UIApplication`: mostly to make the code more testable (always tricky to test code relying on `UIApplication`)
- `openURL` deprecated: you’re right, we should update that
- `LSApplicationQueriesSchemes` in README: great suggestion
- newline in body: I’m not sure, and these third-party apps don’t really have documentation for custom URL scheme support; I would also love to get more feedback on that

**Comment by Seoras** [comment]
I've created an Objective C port and [published it here](https://github.com/Seoras/ThirdPartyMailer).

I've taken a slightly different approach and removed the schemes from the code and placed them in a plist file.

The newline problem I'll add as the first issue to my repo. Hopefully someone has a good suggestion.

Thanks Vincent!
