### ISSUE TITLE
BlindRecipients for Yahoo

### ISSUE THREAD

**Issue by Shannonrob** [vtourraine/ThirdPartyMailer#5]
What would be the correct method to gain access to the "bcc" field just I am currently able to do with the recipient for "to" field. I am fairly new to coding and I've tried changing a few things but failed at getting any access to the "bcc" field.

**Comment by vtourraine** [comment]
Hello (and sorry for the late reply),

The Bcc field is not currently supported by `ThirdPartyMailer`. You could add it as a new parameter, but then we need to find the associated key for each custom URL scheme, _if_ they support it.

Feel free to send a pull request (it doesn’t have to be perfect!), otherwise I’ll consider that for a future update.

Thanks for the suggestion. 👍

**Comment by WurlLink** [comment]
Where do I go to find the custom url in a case like this?

**Comment by vtourraine** [comment]
That’s part of the problem: these apps usually don’t publicly document their custom URL scheme.

You can probably try to guess (`bcc` seems the obvious answer) and test to make sure that the app interprets the parameter as expected.
