### ISSUE TITLE
Adding attachments to the mail with existing clients

### ISSUE THREAD

**Issue by KarrePrakash** [vtourraine/ThirdPartyMailer#7]
How to attach Any file to the email client because its currently  not available in the library provided

**Comment by vtourraine** [comment]
Thank you for your question.

In order to support multiple clients beside the Apple Mail app, this library is based on `mailto:` URLs. They do not support file attachments, so this is not possible in this context.

If you want to prefill an email message with attachments from your iOS app, look at the `MFMailComposeViewController` [documentation](https://developer.apple.com/documentation/messageui/mfmailcomposeviewcontroller) (only supports Apple Mail).

**Comment by CavalcanteLeo** [comment]
is any other way i can attach files?
