### ISSUE TITLE
How make mail Zip file attechment in this ThirdPartyMailer

### ISSUE THREAD

**Issue by saravananr27** [vtourraine/ThirdPartyMailer#8]
_ = ThirdPartyMailer.application(application, openMailClient: client, recipient: "sample@gmail.com", subject: "MyApp", body:Download my App). By using this code implement subject, body and to mail all are implement. How to atteched the Zip file in ThirdPartyMailer help me.

**Comment by vtourraine** [comment]
Thank you for your question.

In order to support multiple clients beside the Apple Mail app, this library is based on `mailto:` URLs. They do not support file attachments, so this is not possible in this context.

If you want to prefill an email message with attachments from your iOS app, look at the `MFMailComposeViewController` [documentation](https://developer.apple.com/documentation/messageui/mfmailcomposeviewcontroller) (only supports Apple Mail).
